include(":bitmap_images")
include(":catalano")
include(":app")
include(":camera_gl")
include(":utils")
include(":common_entities")
include(":core:database:impl")
include(":core:database:api")
