package com.shevelev.wizard_camera.activity_gallery.shared.event_pass

import com.shevelev.wizard_camera.core.ui_utils.fragment_data_pass.FragmentEventPassBase

internal class GalleryFragmentsEventPassImpl : FragmentEventPassBase<GalleryFragmentsEvent>(), GalleryFragmentsEventPass