package com.shevelev.wizard_camera.common_entities.enums

enum class FilterCode(val value: Int) {
    ORIGINAL(0),
    EDGE_DETECTION(1),
    PIXELIZE(2),
    EM_INTERFERENCE(3),
    TRIANGLES_MOSAIC(4),
    LEGOFIED(5),
    TILE_MOSAIC(6),
    BLUE_ORANGE(7),
    CHROMATIC_ABERRATION(8),
    BASIC_DEFORM(9),
    CONTRAST(10),
    NOISE_WARP(11),
    REFRACTION(12),
    MAPPING(13),
    CROSSHATCH(14),
    NEWSPAPER(15),
    ASCII_ART(16),
    MONEY(17),
    CRACKED(18),
    POLYGONIZATION(19),
    BLACK_AND_WHITE(20),
    GRAY(21),
    NEGATIVE(22),
    NOSTALGIA(23),
    CASTING(24),
    RELIEF(25),
    SWIRL(26),
    HEXAGON_MOSAIC(27),
    MIRROR(28),
    TRIPLE(29),
    CARTOON(30),
    WATER_REFLECTION(31)
}