package com.shevelev.wizard_camera.common_entities.enums

enum class FilterCode(val value: Int) {
    ORIGINAL(0),
    EDGE_DETECTION(1),
    PIXELIZE(2),
    TRIANGLES_MOSAIC(3),
    LEGOFIED(4),
    TILE_MOSAIC(5),
    BLUE_ORANGE(6),
    BASIC_DEFORM(7),
    CONTRAST(8),
    NOISE_WARP(9),
    REFRACTION(10),
    MAPPING(11),
    CROSSHATCH(12),
    NEWSPAPER(13),
    ASCII_ART(14),
    MONEY(15),
    CRACKED(16),
    POLYGONIZATION(17),
    BLACK_AND_WHITE(18),
    GRAY(19),
    NEGATIVE(20),
    NOSTALGIA(21),
    CASTING(22),
    RELIEF(23),
    SWIRL(24),
    HEXAGON_MOSAIC(25),
    MIRROR(26),
    TRIPLE(27),
    CARTOON(28),
    WATER_REFLECTION(29)
}